### PR TITLE
Update to version 23.1

### PR DESCRIPTION
**Pull request by kowalski7cc**

### CODE REVIEW

**Comment by kowalski7cc** [comment]
bot, build org.stellarium.Stellarium

**Comment by alex-w** [comment]
@kowalski7cc please try use appdata.xml file from [upstream](https://github.com/Stellarium/stellarium/commit/432c78c2825ff5992a4f551e9f226335daf7b448)

**Comment by kowalski7cc** [comment]
bot, build org.stellarium.Stellarium

**Comment by kowalski7cc** [comment]
@alex-w it seems vcs-browser was correct, it was donate that should be corrected to donation. You can revert https://github.com/Stellarium/stellarium/commit/432c78c2825ff5992a4f551e9f226335daf7b448

**Comment by kowalski7cc** [comment]
@alex-w should be ready for merge. I'd wait for next stellarium release to remove the sed...

**Pull request merged**
